# Generated by Django 4.2.6 on 2023-10-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_cost', models.IntegerField()),
                ('industry', models.CharField(max_length=200)),
                ('legal_business_name', models.CharField(max_length=200)),
                ('business_name', models.CharField(max_length=252)),
                ('business_region_operation', models.CharField(max_length=252)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(max_length=20)),
                ('website', models.URLField()),
                ('has_ein', models.BooleanField(default=False)),
                ('ein', models.CharField(blank=True, max_length=200, null=True)),
                ('business_type', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('timezone', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('client_number', models.CharField(max_length=20)),
                ('job_position', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
            ],
        ),
    ]
