# Generated by Django 4.2.6 on 2023-10-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subaccounts', '0002_subaccount_cell_number_subaccount_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subaccount',
            name='cell_number',
        ),
        migrations.AlterField(
            model_name='subaccount',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
