# Generated by Django 4.2.6 on 2023-10-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subaccounts', '0003_remove_subaccount_cell_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subaccount',
            name='website',
            field=models.TextField(),
        ),
    ]
