# Generated by Django 4.2.6 on 2023-10-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subaccounts', '0004_alter_subaccount_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subaccount',
            name='business_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
