# Generated by Django 4.2.6 on 2023-11-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subaccounts', '0005_calendardetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardetails',
            name='notificationPreference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
