# Generated by Django 4.2.6 on 2023-11-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subaccounts', '0006_contact_tag_purchasedphonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subaccount',
            name='gohighlevel_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subaccount',
            name='gohighlevel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
