# Generated by Django 4.2.6 on 2023-11-20 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subaccounts', '0007_calendardetails_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moreInspections', models.IntegerField(blank=True, null=True)),
                ('jobCapacity', models.IntegerField(blank=True, null=True)),
                ('averageJobs', models.IntegerField(blank=True, null=True)),
                ('paymentMethod', models.CharField(blank=True, max_length=100)),
                ('completionTime', models.IntegerField(blank=True, null=True)),
                ('supplyCostsIncreasing', models.CharField(blank=True, max_length=10)),
                ('priceIncreaseLower', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('priceIncreaseUpper', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offer', models.JSONField(null=True)),
                ('messageSender', models.CharField(blank=True, max_length=100)),
                ('sub_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subaccounts.subaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
